-- 36: drop the two dead AI cache tables.
--
-- `forecasts` and `goal_coach` are the last remains of the v10.x "one card per
-- AI feature" era. Both cached narrative only — every figure they described was
-- recomputed on read — so there is nothing here to migrate, only to remove.
--
--   forecasts   — dead since #232, which folded Home's four AI surfaces into one
--                 panel. The month-ahead Forecast card, its /forecasts/generate
--                 route and ai.generate_forecast() went with it. The ARITHMETIC
--                 survived (compute_forecast() still feeds the month read and
--                 the month_projection Ask tool); only the cache is dead.
--   goal_coach  — dead since #262, which removed the Goal Coach from /goals.
--
-- Filed as #236 for forecasts alone; goal_coach joined it rather than taking a
-- second migration, because a migration stands alone in its own PR and these
-- are one operation on two tables with one reason.
--
-- ── ⚠️ DEPLOY ORDER: THIS GOES *AFTER* THE IMAGE PULL ──────────────────────
--
-- A DROP is the opposite of an additive migration. The running container must
-- ALREADY be the version that no longer references these tables, or the old
-- code SELECTs something that has gone.
--
-- ⚠️ CORRECTED 2026-08-20, at 0.8.0 release prep. This note used to claim
-- "nothing has referenced forecasts since #232 or goal_coach since #263, so
-- the window is empty either way". THAT WAS WRONG, and wrong in an instructive
-- way: it reasoned about `main`, and deploy ordering is only ever about the
-- image that is RUNNING. #232 and #263 both shipped in 0.8.0 — the same release
-- as this migration — so the deployed version at the time this first applies is
-- v0.7.0, which really does read both tables:
--
--     v0.7.0 app/blueprints/forecasts.py:227  SELECT ... FROM forecasts
--     v0.7.0 app/blueprints/forecasts.py:278  INSERT INTO forecasts
--     v0.7.0 app/blueprints/goals.py:310      SELECT ... FROM goal_coach
--     v0.7.0 app/blueprints/goals.py:433      INSERT INTO goal_coach
--
-- ⚠️ And release.yml applies pending migrations BEFORE it pulls the image, so
-- this DROP lands while the old container is still serving. That was accepted
-- deliberately for the 0.8.0 deploy (Sean, 2026-08-20): one user, a deploy he
-- triggers and watches, a window the length of an image pull, a pg_dump taken
-- first, and no data at risk — the cost is a 500 on `/` or `/goals` if either
-- is loaded in that minute.
--
-- ⚠️ DO NOT GENERALISE THAT ACCEPTANCE. It rests on this application having one
-- user. The next DROP whose tables the deployed image still reads needs the
-- real answer: hold the migration back one release, so the running image no
-- longer references them by the time it applies.
--
-- ── ⚠️ ONE-WAY DOOR ────────────────────────────────────────────────────────
--
-- pg_dump first. These tables hold every forecast and coaching narrative ever
-- generated for every user. Nothing reads them and nothing can regenerate them
-- — the features are gone. Taking the dump is the only thing that makes this
-- reversible.
--
-- ── Older backups still contain them ───────────────────────────────────────
--
-- The retained dumps predate this migration and will carry both tables for as
-- long as they are kept. That is fine and needs no handling:
-- scripts/restore_check.py deliberately has NO expected-table list (see the
-- comment there), so a dump containing tables the current schema lacks still
-- validates. Restoring one into a fresh database recreates them, empty and
-- unreferenced; re-applying this migration removes them again.
--
-- IF EXISTS on both, so a re-run is a no-op rather than an error.

BEGIN;

DROP TABLE IF EXISTS public.forecasts;
DROP TABLE IF EXISTS public.goal_coach;

COMMIT;
